spring:
  cloud:
    gcp:
      credentials:
        location: ${GOOGLE_CREDENTIAL_FILE_LOCATION:classpath:springboot2-fcm-1a7b157dea33.json}
      project-id: ${GOOGLE_PROJECT_ID:springboot2-fcm}
      pubsub:
        credentials:
          location:
  application:
    name: springboot-google-cloud-fcm
server:
  servlet:
    context-path: /google-fcm
  port: ${APPLICATION_PORT:8080}
